= MP Metrics sample

This repo contains a sample of how the http://microprofile.io/[Eclipse Microprofile] spec apis could look like.
There is no spec yet and this sample is for illustration purposes.

== Building

----
$ mvn install
----

This will build the app and run on WildFly Swarm.

Tests in `src/it/java/de/bsd/mp_metrics/it/MpMetricsIT` are then run against that Swarm instance

== Running

----
$ java -jar target/mp-metrics-swarm.jar -Dmapping=src/main/resources/de/bsd/mp_metrics/mapping.yml
----

=== Obtaining data via the REST-Interface

.Retrieving all metrics
----
$ curl -i -X GET localhost:8080/metrics/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json
Content-Length: 166
Date: Fri, 05 May 2017 09:26:01 GMT

{
  "application":{"demo":0},
  "vendor":{"msc-loaded-modules":244},
  "base":{"peak-thread-count":62,
          "max-heap":3817865216,
          "thread-count":39,
          "total-started-thread-count":69}}
----



.Retrieving only application specific metrics
----
$ curl -i -X GET localhost:8080/metrics/application
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json
Content-Length: 10
Date: Fri, 05 May 2017 09:27:44 GMT

{"demo":0}
----

.Retrieving vendor-specific meta data
----
$ curl -i -X OPTIONS localhost:8080/metrics/vendor
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json
Content-Length: 220
Date: Fri, 05 May 2017 09:28:32 GMT

[
  {"name":"msc-loaded-modules",
  "displayName":"msc-loaded-modules",
  "description":"Number of loaded modules",
  "type":"gauge",
  "unit":"none"
 }
]
----

=== Prometheus text format

It is also possible to retrieve metric values (along with part of the metadata):

.Retrive data in Prometheus format
----
 curl -i -X GET -HAccept:text/plain http://localhost:8080/metrics/
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/plain
Content-Length: 609
Date: Fri, 12 May 2017 15:35:31 GMT

# TYPE base:thread_count gauge
base:thread_count{tier="integration"} 43
# TYPE base:peak_thread_count gauge
base:peak_thread_count{tier="integration"} 62
# TYPE base:total_started_thread_count counter
base:total_started_thread_count{tier="integration"} 73
# TYPE base:max_heap counter
base:max_heap{domain="memory",type="heap",tier="integration"} 3817865216
# TYPE vendor:msc_loaded_modules gauge
vendor:msc_loaded_modules{tier="integration"} 244
# TYPE application:ola gauge
application:ola{app="ola",tier="integration"} 42
# TYPE application:hello counter
application:hello{app="shop",tier="integration"} 0
----



== Using in Applications

`DemoBean` is showing how to submit metrical values in application code.
These are registered, in `MpMetricApplication#registerMetricsForDemoBean` which is the Jax-RS `Application` class
for the entire application.